#!/usr/bin/env bash

# git hook post-merge
# 
# set of fo GIT rules to facilitate work with Laravel
#
# author Bielecki Krzysztof

# get list from last pull
changedFiles="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

# check changes in composer
echo "$changedFiles" | grep --quiet -i "composer.json" && eval "composer install"
# check changes in bower
echo "$changedFiles" | grep --quiet -i "bower.json" && eval "bower update"
# check new migrations
echo "$changedFiles" | grep --quiet -i "migrations" && eval "php artisan migrate"
# check changes or new files for grunt
# in [] write action name for build js css file
echo "$changedFiles" | grep --quiet -E -i "\.(.css|less|js)" && eval "grunt [action] && npm run [action]"
# check changes in NodeJS
echo "$changedFiles" | grep --quiet -i "package.json" && eval "npm install"

