#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

RULESET=./phpcs.xml

# Check for phpcbf
which phpcbf &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install PHPCBF"
  exit 1
fi

echo "Fixing by:"

for FILE in $STAGED_FILES
do
  phpcbf --standard="$RULESET" "$FILE"
  git add "$FILE"
done

PASS=true

echo "Validating PHPCS:"

# Check for phpcs
which phpcs &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install PHPCS"
  exit 1
fi

for FILE in $STAGED_FILES
do
  phpcs --standard="$RULESET" "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "PHPCS Passed: $FILE"
  else
    echo "PHPCS Failed: $FILE"
    PASS=false
  fi
done

echo "PHPCS validation completed!"

if ! $PASS; then
  echo "COMMIT FAILED: Your commit contains files that should pass PHPCS but do not. Please fix the PHPCS errors and try again."
  exit 1
else
  echo "COMMIT SUCCEEDED"
fi

exit $?
